ALL TESTS PASS (except for newAvailTest()).
com.avail.exceptions:
AmbiguousNameException: New exception.
AvailErrorCode: Added E_AMBIGUOUS_INSTANCE_OF_METATYPE_SMEAR, E_NONPOSITIVE_METATYPE_LEVEL, E_OBJECT_TYPE_HAS_NO_USER_DEFINED_NAME, E_NO_IMPLEMENTATION_SET, E_WRONG_NUMBER_OF_OUTERS, E_KEY_NOT_FOUND, E_NEGATIVE_SIZE, E_IO_ERROR, E_PERMISSION_DENIED, E_INVALID_HANDLE, E_INVALID_PRIMITIVE_NUMBER, E_CLOSURE_DISAGREES_WITH_PRIMITIVE_RESTRICTION, E_LOCAL_TYPE_LITERAL_IS_NOT_A_TYPE, E_OUTER_TYPE_LITERAL_IS_NOT_A_TYPE, E_UNHANDLED_EXCEPTION, E_SIGNATURE_DOES_NOT_SUPPORT_REQUIRES_CLOSURE, E_SIGNATURE_DOES_NOT_SUPPORT_RETURNS_CLOSURE, E_INVALID_SPECIAL_OBJECT_NUMBER, E_MACRO_ARGUMENT_MUST_BE_A_PARSE_NODE, E_AMBIGUOUS_NAME, E_DECLARATION_KIND_DOES_NOT_SUPPORT_ASSIGNMENT, E_DECLARATION_KIND_DOES_NOT_SUPPORT_REFERENCE.

com.avail.interpreter:
Interpreter: lookupName() now throws AmbiguousNameException.
Primitive: Completed phase one refactor of primitives to use AvailErrorCodes.