ALL TESTS PASS.
[Avail]
/avail/Avail/Foundation:
Exception: "Guard|guard_«intercept_»«ensure_»" is now a macro, and no
longer needs to generate functions at runtime in order to appropriately
wrap handlers for unwinds.