ALL TESTS PASS (except for newAvailTest()).
Primitive failure codes are now (mostly) numeric. The ultimate goal is to remove all failure messages from the VM; internationalization belongs in the Avail code base (or beyond).

Began work on subprimitive exception refactoring. Henceforth subprimitive operations, implemented on descriptor classes, should raise subclasses of AvailException with appropriate AvailErrorCodes to report failure to Avail primitives. The primitives may then extract the numeric values of the AvailErrorCodes and write them into the primitive failure variables for primitive fallback code to convert into Avail exceptions.

com.avail.descriptor:
AvailObject: Operations related to addition and subtraction of integral values are now documented. They also declare check exceptions where appropriate.
Descriptor: subclassResponsibility() is now unsupportedOperation(). It now uses reflection to report its caller's name. It throws an UnsupportedOperationException.
*: Changes to support raising ArithmeticException from subprimitives.

com.avail.exceptions: New package.
AvailErrorCode: New enum. Describes exceptional conditions within the VM.
AvailException: New exception. Takes an AvailErrorCode (and maybe a Throwable). Provides a numeric error code as an AvailObject for convenient use by primitives.
UnsupportedOperationException: New exception. Replaces use of AvailObject#error() for AvailObject#subclassResponsibility() (now unsupportedOperation()).
ArithmeticException: New exception. Describes exceptional arithmetic conditions (e.g. addition of unlike infinities, division by zero, etc.).

com.avail.interpreter:
Primitive: The default privateFailureVariableType() is now natural number. Primitives 1 and 2 now rely on ArithmeticException to avoid redundant argument validity checks (and accordingly simplify code). Primitive 200's failure variable type is now [0..0]. Primitives 350, 353, and 354's failure variable type is temporarily string; it should eventually use natural number like the others.