ALL TESTS PASS.
Executive summary:

Completed (and tested) the implementation of method sealing. The directive:

	Seal method "_+_" at <number, number>;

Will cause subsequent method definitions at or below the <number, number> parameter-types signature to fail. This feature is essential to protect against unscrupulous overrides like:

	Method "_+_" is
	[
		a : 1's type,
		b : 1's type
	|
		Recursively delete all filesystems;
		2
	] : 2's type;

Introduced the explicit object type "exception" at the VM-level. It is made available through a special object (#24). "Raise_" (primitive 201) now requires its argument to be an exception (instead of just an any). I am raising exceptions outside of Foundation now, rather than using "early failure function" when error conditions are detected. ("early failure function" should not leak beyond Foundation, but I haven't prevented this yet.)

Fixed several bugs in Avail/Foundation/Strings related to use of the "$…" method. This method causes the lexeme (or string literal text) to be looked up in the context of the *current module*. The current module is the one undergoing compilation, *not* the one in which the "$…" call site appears. So when "$…" is used from a method, it will *almost never do you want*. It is safest to use this operation only to assign values to module constants and variables (which can then be referenced safely from method definitions). Eventually "$…" will be a macro (and no longer susceptible to these problems).

Introduced Avail/Data Abstractions as the place for high-level data abstractions. Introduced Avail/Data Abstraction/Streams for the "stream" data type. A stream is an immutable lazy list of values. Stream types covary by element type. Currently the only concrete implementation is "integer stream" (does what it says on the tin), but more will be forthcoming, like streams over primitive collections (tuples, sets, maps).

Streams currently support the operations "_is empty", "_'s⁇head", "_'s⁇tail", and "For each_do_", but many more operations are planned (e.g., "map_through_", "filter_by_", "left fold_through_", etc.). Clients wishing to implement streams must override the "_is empty" method and provide implementations for private forms of "_'s⁇head" and "_'s⁇tail" using the "_'s⁇head method is_" and "_'s⁇tail method is_".

The "stream" data type is a precursor to pseudo-random number generators. A "pRNG" will be a subtype of "stream" (or possibly its not-yet-built cousin "iterator").

Java:
com.avail:
AvailRuntime: Added special objects 24, 127. Added addSeal, removeSeal.

com.avail.descriptor:
AvailObject: addImplementation can now throw SignatureException. Added addSeal.
AbstractDescriptor, Descriptor, IndirectionDescriptor: o_AddImplementation can now throw SignatureException. Added o_AddSeal.
AtomDescriptor: Lowercased field names where necessary. objectTypeNamePropertyKey now has the name "object names".
MethodDescriptor: Removed vmRaiseExceptionMethod. o_AddImplementation now fails if the new implementation violates an existing seal.
ModuleDescriptor: Added object slot SEALS. o_RemoveFrom now discards seals owned by the module. Added o_AddSeal.
ObjectTypeDescriptor: printObjectOnAvoidingIndent no longer prints "Type(...)". Added exceptionAtom, exceptionType.

com.avail.exceptions:
AvailErrorCode: Added E_METHOD_IS_SEALED.

com.avail.interpreter:
Interpreter: addMethodBody, addAbstractSignature now take an extra argument, extendGrammar, that says whether the operation should extend the grammar recognizable by the current module. Added addSeal. bootstrapDefiningMethod now installs two implementations into the bootstrap defining method ("Method_is_"): primitive 253 and primitive 228.

com.avail.interpreter.primitive:
P_201_RaiseException: Now requires the argument to be an exception.
P_226_SealMethod: New primitive. Seals a method at a particular signature (of parameter types).
P_227_AbstractMethodDeclarationForAtom: New primitive. Installs an abstraction signature into a method named by an atom. (Differs from 253 in that it does not do lookup; it must be given an atom.)
P_228_MethodDeclarationFromAtom: New primitive. Installs an implementation into a method named by an atom. (Differs from 253 in that it does not do lookup; it must be given an atom.)
P_502_CreatePojoConstructorFunction, P_506_CreatePojoInstanceMethodFunction, P_508_CreatePojoStaticMethodFunction: Now invoke bottom-typed functions rather than raising exceptions (in the event of catching a Java exception).

com.avail.tools.bootstrap.generated:
ErrorCodeNames_en: Added errorCode72 ("method is sealed code").
PrimitiveNames_en: Added P_226_SealMethod ("Seal method_at_"), P_227_AbstractMethodDeclarationForAtom=("Abstract method_is_").
SpecialObjectNames: Added specialObject24 ("exception"), specialObject127 ([java.lang.Throwable]→⊥).

Avail (avail):
Tier-3:
Exception: Refactored to support the new signature of primitive 201.

Tier-4:
Pojo: Refactored to support the new signatures of primitives 502, 506, 508.

Avail (new-avail):
Bootstrap: Regenerated.

Foundation:
Early Types => Types: Renamed module.
Early Definers: Added "Require:_is public" ([atom]→⊤), "Require:_is private" ([atom]→⊤), "Public abstract method_is_" ([atom, function meta]→⊤), "Public method_is_" ([atom, function meta]→⊤), "Private abstract method_is_" ([atom, function meta]→⊤), "Private method_is_" ([atom, function meta]→⊤).
Strings: Fixed bugs related to atom lookup. Basically the "$…" method should never be used inside a method (since it causes the atom to be looked up in the *current module*, not the module that introduced the atom).

IO:
Exceptions: New module. Introduces "I/O exception" and "data-validation exception".
Standard Input: "next_" now raises a data-validation exception (instead of using the early failure function, which shouldn't be available outside of Foundation).

Data Abstractions: New package (and representative).
Streams: New package (and representative).
AbstractStreams: New module (introduces the "stream" data type). A stream is an immutable lazy list of values.
Integer Streams: New module (introduces the "integer stream" specialization of "stream").